title: Marina Gardella
description: Project scientist at Centro Pi - IMPA
site_title: '@marinagardella - Marina Gardella'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: marinagardella
email: marigardella@gmail.com
twitter_username: GardellaMarina


# absolute or relative
profile_picture: assets/images/photo.jpg

# Google Analytics ID
google_analytics: 
